name: deploy
on:
  push:
    tags:
      - '*'

jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Restore
        run: dotnet restore
      - name: Build Windows
        run: dotnet publish -c Release -r win-x64 AvaloniaTest/AvaloniaTest.csproj
      - name: Build Linux
        run: dotnet publish -c Release -r linux-x64 AvaloniaTest/AvaloniaTest.csproj
      - name: Build Mac
        run: dotnet publish -c Release -r osx-x64 AvaloniaTest/AvaloniaTest.csproj
      - name: Zip Windows
        run: zip -r windows-x64.zip publish/win-x64/AvaloniaTest/
      - name: Zip Linux
        run: zip -r linux-x64.zip publish/linux-x64/AvaloniaTest/
      - name: Zip Mac
        run: zip -r osx-x64.zip publish/osx-x64/AvaloniaTest/
      - name: Upload Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-x64.zip
          asset_name: windows-x64.zip
          asset_content_type: application/zip