name: deploy
on:
  push:
    tags:
      - '*'

jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet publish -c Release -r win-x64 AvaloniaTest/AvaloniaTest.csproj
        run: dotnet publish -c Release -r linux-x64 AvaloniaTest/AvaloniaTest.csproj
        run: dotnet publish -c Release -r osx-x64 AvaloniaTest/AvaloniaTest.csproj